// import Link from 'next/link'
// import React from 'react'
// import Head from 'next/head'
// // import connectDb from "../../middleware/mongoose"
// import mongoose from 'mongoose'
// import Product from './models/Product'


// const Headphons = ({ products }) => {
//   return (
//     <div>

//       <Head>
//         <title>Wellcome to T - Shirt's Page</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32-32.png" />
//       </Head>

//       <section className="text-gray-600 body-font">
//         <div className="container px-5 py-24 mx-auto">
//           <div className="flex flex-wrap -m-4 justify-center">
//             {products.map((item) => {
//               return <Link legacyBehavior key={item._id} className="block relative rounded overflow-hidden" href={'/product/${item.slug}'}><div className="lg:w-1/5 md:w-1/2 p-4 w-full cursor-pointer shadow-md rounded m-5">
//                 <a className='block relative rounded overflow-hidden'>
//                   <img alt="ecommerce" className=" mx-auto h-[36vh] block" src={item.img} />
//                 </a>
//                 <div className="mt-4 text-center">
//                   <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">{item.category}</h3>
//                   <h2 className="text-gray-900 title-font text-lg font-medium">{item.title}</h2>
//                   <p className="mt-1">₹ {item.price}</p>
//                   {/* <p className="mt-1">S , M , L , XL , XXL</p> */}
//                 </div>
//               </div>
//               </Link>
//             })}
//           </div>
//         </div>

//       </section >
//     </div >
//   )
// }

// export async function getServerSideProps(context) {
//   if (!mongoose.connections[0].readyState) {
//     await mongoose.connect(process.env.MONGO_URI)
//   }
//   let products = await Product.find({category: 'Mug'}) //  // if you not 
//   return {
//     props: { products: JSON.parse(JSON.stringify(products)) }, // will be passed to the page component as props
//   }
// }

// export default Headphons


// For Headphons


import Link from 'next/link'
import React from 'react'
import Head from 'next/head'
// import connectDb from "../../middleware/mongoose"
import mongoose from 'mongoose'
import Product from './models/Product'


const Headphons = ({ products }) => {
  return (
    <div>

      <Head>
        <title>Wellcome to T - Shirt's Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32-32.png" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4 justify-center">
            {products.map((item) => {
              return <Link legacyBehavior key={item._id} className="block relative rounded overflow-hidden" href={'/product/${item.slug}'}><div className="lg:w-1/5 md:w-1/2 p-4 w-full cursor-pointer shadow-md rounded m-5">
                <a className='block relative rounded overflow-hidden'>
                  <img alt="ecommerce" className=" mx-auto h-[36vh] block" src={item.img} />
                </a>
                <div className="mt-4 text-center">
                  <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">{item.category}</h3>
                  <h2 className="text-gray-900 title-font text-lg font-medium">{item.title}</h2>
                  <p className="mt-1">₹ {item.price}</p>
                  {/* <p className="mt-1">S , M , L , XL , XXL</p> */}
                </div>
              </div>
              </Link>
            })}
          </div>
        </div>

      </section >
    </div >
  )
}

export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI)
  }
  let products = await Product.find({category: 'Headphon'}) //  // if you not 
  return {
    props: { products: JSON.parse(JSON.stringify(products)) }, // will be passed to the page component as props
  }
}

export default Headphons